### PR TITLE
Fix bugs found on new account creation

### LINKED ISSUE #308: Bugs on Account Creation
Created a new trial account with a car mileage of 100miles and there were two ToDo cards for the oil and tire rotation todos.

### PR DESCRIPTION
**Pull request by baylessj**
Closes #308.

### CODE REVIEW

File: lib/models/src/todo_due_state.dart [hunk 1]
```diff
@@ -5,4 +5,6 @@ const DUE_SOON_CUTOFF_TIME = 14;
 
 /// Used to determine if a ToDo is DUE_SOON when there is not enough data for
 /// the car to have a distanceRate value.
-const DEFAULT_DUE_SOON_CUTOFF_DISTANCE_RATE = 10;
+/// Average person drives ~13,500mi a year, so roughly 40mi per day, which is
```
Comment (DavBfr) [inline lib/models/src/todo_due_state.dart:8]: Some stats here for the US: https://www.carinsurance.com/Articles/average-miles-driven-per-year-by-state.aspx
you could add as comment.
